### ISSUE TITLE
Error: Cannot find module 'xmldom'

### ISSUE THREAD

**Issue by smoebody** [nickdesaulniers/javascript-playlist-parser#11]
it seems that xmldom is a dependency by playlist-parser but its missing in the package.jsons `dependencies` section

**Comment by nickdesaulniers** [comment]
it's listed in devDependencies.

https://github.com/nickdesaulniers/javascript-playlist-parser/blob/master/package.json#L34

How are you installing this lib?

**Comment by chovy** [comment]
why is it in devDependencies?

**Comment by nickdesaulniers** [comment]
because the final product compiled can just be downloaded from https://github.com/nickdesaulniers/javascript-playlist-parser/blob/master/lib/parser.min.js.  You can download it if you plan on developing this lib, then emitting a new build.  Thus, it is a dev dependency.  The minified build is also the entry point when installed as a node.js module: https://github.com/nickdesaulniers/javascript-playlist-parser/blob/master/package.json#L5

**Comment by chovy** [comment]
When I do `npm install playlist-parser` and run it I get an error, because the required dependency `xmldom` is not installed. It should be a regular dependency for node, not in `devDependencies`.

**Comment by nickdesaulniers** [comment]
Is this something that changed recently in npm?  I thought you had to be explicit about _not checking out_ dev dependencies?  Are you sure that you don't have some kind of global npm setting that doesn't check out dev dependencies by default?

**Comment by chovy** [comment]
Its not a dev dependency though :) --- its required to run.
